Repository Think-Tank-6/VOS-client, pull requests merged in 2024-01, with the labels that each got.

#22 [feat #21] generate 파일 수정
  assets/img/loading.gif
  component/generate.js
  component/loading.js
  package-lock.json
  package.json
Labels: feat

#26 [feat #24] 카카오 API.js업데이트 추가 수정
  .env
  .gitignore
  app.json
  component/kakao_login.js
Labels: feat

#28 [fix #27] .env 삭제
  .env
Labels: fix, emergency

#35 [fix #34] package.json 수정
  package.json
Labels: fix, emergency

#29 [feat #23] 채팅 기능 추가
  component/chat.js
  hooks/useSocket.js
Labels: feat

#38 [feat #37] 카카오 로그인 코드 변경 및 회원가입 에러 수정
  component/join.js
  component/kakao_login.js
Labels: feat

#42 [feat #39] 마이페이지 백엔드 연결전
  App.js
  assets/favicon.png
  component/ground.js
  component/join.js
  component/kakao_login.js
  component/login.js
  component/mypage.js
  component/pwupdate.js
  component/setting.js
  component/starList.js
Labels: feat

#44 [feat #43] 회원가입 이메일 중복체크
  App.js
  component/join.js
Labels: feat

#47 [fix] plus icon 추가 및 package.json 업데이트
  assets/img/plus.png
  component/starList.js
  package-lock.json
  package.json
Labels: fix, emergency

#48 [fix #46] API_URL 추가 수정
  admin/components/userDetail.js
  admin/components/userList.js
  component/join.js
  component/kakao_login.js
  component/login.js
  component/mypage.js
  component/starList.js
Labels: fix, emergency

#61 [feat #52] AI 모델 및 백엔드 연결 완료
  App.js
  component/chat.js
  component/starList.js
  hooks/useSocket.js
  package-lock.json
  package.json
Labels: feat

#63 [feat #62] 채팅방 아바타 (프로필 이미지) 가져오기
  component/chat.js
Labels: feat

#69 [fix #68] gender 추가오류 수정
  component/generate.js
Labels: fix

#79 [fix #78] 채팅 아바타 랜더링 오류 해결
  component/chat.js
  component/starList.js
  package-lock.json
  package.json
Labels: fix

#77 [feat #76] Voice Cloning 호출
  component/chat.js
  package-lock.json
  package.json
Labels: feat

#84 [fix #83] starList image 오류 수정
  component/starList.js
Labels: fix

#89 [feat #88] 로그아웃 기능 추가
  auth/login.js
  component/main.js
  component/setting.js
  component/starList.js
Labels: feat

#90 [feat #81] star Image, name 수정, star 삭제기능추가
  component/starList.js
Labels: feat

#93 [fix #92] generate 종료시 모달 닫기
  component/generate.js
  component/starList.js
Labels: fix

#96 [feat #80] 음성복원 기능 추가
  component/chat.js
  package-lock.json
  package.json
Labels: feat

#99 [fix #98] Alert 오류 수정
  component/generate.js
  component/starList.js
Labels: fix

#104 [refactor #101] 주석 및 로그 삭제
  admin/components/adminJoin.js
  admin/components/adminList.js
  admin/components/userDetail.js
  admin/components/userDetail2.js
  admin/components/userList.js
  assets/img/icon.png
  auth/ground.js
  auth/join.js
  auth/kakao_login.js
  auth/login.js
  component/chat.js
  component/delete.js
  component/generate.js
  component/loading.js
  component/main.js
  component/member.js
  component/pwupdate.js
  component/setting.js
  component/starList.js
  hooks/useSocket.js
  package-lock.json
Labels: refactor

#106 [build #100] 배포 준비
  app.json
  eas.json
  package-lock.json
  package.json
Labels: build
